name: silence_score
description: A Flutter app that measures silence and awards points for maintaining quiet environments.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.3+1
  noise_meter: ^5.1.0
  shared_preferences: ^2.5.3
  confetti: ^0.8.0
  permission_handler: ^12.0.1
  fl_chart: ^1.0.0
  purchases_flutter: ^9.2.1
  purchases_ui_flutter: ^9.2.1 # RevenueCat native paywall UI (aligned with purchases_flutter)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  csv: ^6.0.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  device_info_plus: ^11.5.0
  vibration: ^3.1.3
  flutter_tts: ^4.2.3
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 
  generate: true