#!/bin/bash
# RevenueCat Dashboard Configuration Checklist

echo "🔧 REVENUECAT DASHBOARD CONFIGURATION CHECKLIST"
echo "==============================================="
echo ""
echo "⚠️  Current Issue: ConfigurationError - No products registered"
echo "✅ Solution: Configure products and offerings in RevenueCat dashboard"
echo ""
echo "📋 STEPS TO FIX:"
echo ""
echo "1. 🌐 Go to RevenueCat Dashboard"
echo "   → https://app.revenuecat.com/"
echo "   → Select your SilenceScore project"
echo ""
echo "2. 📦 Add Products (Products section):"
echo "   → Click 'Add Product'"
echo "   → Product ID: premium.tier:monthly"
echo "   → Display Name: Premium Monthly"
echo "   → Type: Subscription"
echo "   → Store: Google Play"
echo ""
echo "   → Click 'Add Product' again"
echo "   → Product ID: premium.tier:yearly"
echo "   → Display Name: Premium Yearly"
echo "   → Type: Subscription"
echo "   → Store: Google Play"
echo ""
echo "3. 🎯 Add Entitlement (Entitlements section):"
echo "   → Click 'Add Entitlement'"
echo "   → Entitlement ID: premium"
echo "   → Display Name: Premium Access"
echo ""
echo "4. 🎁 Create Offering (Offerings section):"
echo "   → Click 'Add Offering'"
echo "   → Offering ID: current"
echo "   → Display Name: Current Offering"
echo "   → Add both products to this offering"
echo "   → Link entitlement 'premium' to both products"
echo ""
echo "5. ✅ Set as Current Offering:"
echo "   → Mark 'current' offering as the current/default offering"
echo ""
echo "🔄 After Configuration:"
echo "   → The ConfigurationError will disappear"
echo "   → Subscription purchases will work"
echo "   → Mock purchases will work in sandbox"
echo ""
echo "🧪 Test Again:"
echo "   → Open app → Settings → Subscribe → Should work!"
echo ""
echo "💡 Alternative Quick Fix:"
echo "   → Change product IDs in dashboard to match existing code:"
echo "   → premium_monthly_199 (instead of premium.tier:monthly)"
echo "   → premium_yearly_999 (instead of premium.tier:yearly)"
