#!/bin/bash
# RevenueCat Sandbox Testing Guide for Focus Field

echo "🧪 REVENUECAT SANDBOX TESTING GUIDE"
echo "=================================="
echo ""
echo "✅ Current Status:"
echo "  - App running with sandbox mode enabled"
echo "  - Mock subscriptions disabled"
echo "  - Using Android API key: goog_OQmcHbcdgUgLCplNGOzHRVwfqVU"
echo ""
echo "📱 Testing Steps:"
echo "1. Open the app on your Android device (moto g play)"
echo "2. Navigate to Settings (tap the settings icon)"
echo "3. Look for 'Upgrade to Premium' or subscription options"
echo "4. Try to purchase a subscription"
echo ""
echo "🎯 Expected Products in Dashboard:"
echo "  - premium.tier:monthly"
echo "  - premium.tier:yearly"
echo ""
echo "🎯 Expected Entitlement:"
echo "  - premium"
echo ""
echo "⚠️  Current Issue:"
echo "  Product IDs in code don't match dashboard:"
echo "  Code expects: premium_monthly_199, premium_yearly_999"
echo "  Dashboard has: premium.tier:monthly, premium.tier:yearly"
echo ""
echo "🔧 Quick Fix Options:"
echo "  A) Update dashboard products to match code"
echo "  B) Code already updated to match dashboard (recommended)"
echo ""
echo "📊 Testing What to Look For:"
echo "  - No 'ConfigurationError' in logs"
echo "  - Offerings load successfully"
echo "  - Purchase flow initiates without errors"
echo "  - User tier updates after purchase"
echo ""
echo "🐛 If Testing Fails:"
echo "  1. Check if products are configured in RevenueCat dashboard"
echo "  2. Verify offerings are set up"
echo "  3. Ensure entitlements are linked to products"
echo "  4. Check Flutter console for specific error messages"
echo ""
echo "⏰ Run this periodically to check logs:"
echo "flutter logs"
